-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Adresler" DROP CONSTRAINT IF EXISTS "Adresler_Musteriler_FK";

ALTER TABLE IF EXISTS public."Bilancolar" DROP CONSTRAINT IF EXISTS "Bilancolar_Musteriler_FK";

ALTER TABLE IF EXISTS public."GercekMusteriler" DROP CONSTRAINT IF EXISTS "GercekMusteriker_Musteriler_FK";

ALTER TABLE IF EXISTS public."Musteriler" DROP CONSTRAINT IF EXISTS "Musteriler_Kanallar_FK";

ALTER TABLE IF EXISTS public."TicariFaaliyetler" DROP CONSTRAINT IF EXISTS "TicariFaaliyetler_GercekMusteriler_FK";

ALTER TABLE IF EXISTS public."TuzelMusteriler" DROP CONSTRAINT IF EXISTS "TuzelMusteriler_Musteriler_FK";

ALTER TABLE IF EXISTS public."Sendikalar" DROP CONSTRAINT IF EXISTS "Sendikalar_Musteriler_FK";



DROP TABLE IF EXISTS public."Adresler";

CREATE TABLE IF NOT EXISTS public."Adresler"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriId" integer NOT NULL,
    "AdresDetay" character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Adresler_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Bilancolar";

CREATE TABLE IF NOT EXISTS public."Bilancolar"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriId" integer NOT NULL,
    "Tarih" date NOT NULL,
    "Tutar" money NOT NULL,
    CONSTRAINT "Bilancolar_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."GercekMusteriler";

CREATE TABLE IF NOT EXISTS public."GercekMusteriler"
(
    "MusteriId" integer NOT NULL,
    "Ad" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Soyad" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TcKimlikNo" character varying(11) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "GercekMusteriler_pkey" PRIMARY KEY ("MusteriId"),
    CONSTRAINT "UK_GercekMusteriler_TcKimlikNo" UNIQUE ("TcKimlikNo")
);

DROP TABLE IF EXISTS public."Kanallar";

CREATE TABLE IF NOT EXISTS public."Kanallar"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ad" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Kanallar_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Musteriler";

CREATE TABLE IF NOT EXISTS public."Musteriler"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriNo" character varying COLLATE pg_catalog."default" NOT NULL,
    "KanalID" integer NOT NULL,
    CONSTRAINT "Musteriler_pkey" PRIMARY KEY (id),
    CONSTRAINT "UK_Musteriler_MusteriNo" UNIQUE ("MusteriNo")
);

DROP TABLE IF EXISTS public."TicariFaaliyetler";

CREATE TABLE IF NOT EXISTS public."TicariFaaliyetler"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GercekMusteriId" integer NOT NULL,
    "BaslangicTarihi" date NOT NULL,
    CONSTRAINT "TicariFaaliyetler_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."TuzelMusteriler";

CREATE TABLE IF NOT EXISTS public."TuzelMusteriler"
(
    "MusteriId" integer NOT NULL,
    "Unvan" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "VergiNo" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TuzelMusteriler_pkey" PRIMARY KEY ("MusteriId")
);

DROP TABLE IF EXISTS public."Sendikalar";

CREATE TABLE IF NOT EXISTS public."Sendikalar"
(
    "MusteriId" integer NOT NULL,
    "Ad" character varying(50) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

ALTER TABLE IF EXISTS public."Adresler"
    ADD CONSTRAINT "Adresler_Musteriler_FK" FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bilancolar"
    ADD CONSTRAINT "Bilancolar_Musteriler_FK" FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."GercekMusteriler"
    ADD CONSTRAINT "GercekMusteriker_Musteriler_FK" FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "GercekMusteriler_pkey"
    ON public."GercekMusteriler"("MusteriId");


ALTER TABLE IF EXISTS public."Musteriler"
    ADD CONSTRAINT "Musteriler_Kanallar_FK" FOREIGN KEY ("KanalID")
    REFERENCES public."Kanallar" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TicariFaaliyetler"
    ADD CONSTRAINT "TicariFaaliyetler_GercekMusteriler_FK" FOREIGN KEY ("GercekMusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TuzelMusteriler"
    ADD CONSTRAINT "TuzelMusteriler_Musteriler_FK" FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "TuzelMusteriler_pkey"
    ON public."TuzelMusteriler"("MusteriId");


ALTER TABLE IF EXISTS public."Sendikalar"
    ADD CONSTRAINT "Sendikalar_Musteriler_FK" FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;